#!/bin/murgaLua

--[[ 
--- Questions to answer:
-where are all your data?
-where are the "fullest" directories?
---- Problems to resolve
1/ fine-tune windows / linux command lines for getting directories' size
2/ process text files with dirs'size
3/ define vizualisation's charts 
4/ zooming on charts ?
]]

i=0
f=0
st=""
-- BUFFER and vars for file -----------------------------------------------
separator = ";"
read_data = "" --read buffer
size_eol = 0 -- EOL size Unix / MacOs / Windows
-- GUI variables ----------------------------------------------------------
width_pwindow = 500 --dim main window for wordcloud
height_pwindow = 500
width_button = 160
height_button = 40
dec_button = 0
--cwindow=nil -- window for charts/stats
--pie=nil --var for charts
--width_cwindow = 500 --dim window for charts/stats
--height_cwindow = 500
decx_chart   = 20 --dim & position charts in this widow
decy_chart   = 0
width_chart  = 450
height_chart = 450
centerw=(width_pwindow/2)
centerh=((height_pwindow-height_button)/2)
ran,rad=0,0


dirs_labels={}
dirs_labels_ASCII={}
dirs_size={}
dirs_size_label={} --size "string formatted" 4,4G ou 163M ou 144k
dirs_button={}

-- encoding cars -------------------------------------------------------
table_convert={}
convert={ascii_car={}, 
         ascii_char={}
        }
convert.ascii_car[1]="é"
convert.ascii_char[1]="e"
convert.ascii_car[2]="É"
convert.ascii_char[2]="E"
convert.ascii_car[3]="à"
convert.ascii_char[3]="a"
convert.ascii_car[4]="À"
convert.ascii_char[4]="A"
convert.ascii_car[5]="è"
convert.ascii_char[5]="e"
convert.ascii_car[6]="È"
convert.ascii_char[6]="E"
convert.ascii_car[7]="ô"
convert.ascii_char[7]="o"
convert.ascii_car[8]="Ô"
convert.ascii_char[8]="O"
convert.ascii_car[9]="ê"
convert.ascii_char[9]="e"
convert.ascii_car[10]="Ê"
convert.ascii_char[10]="E"
convert.ascii_car[11]="î"
convert.ascii_char[11]="i"
convert.ascii_car[12]="Î"
convert.ascii_char[12]="I"
convert.ascii_car[13]="ù"
convert.ascii_char[13]="u"
convert.ascii_car[14]="Ù"
convert.ascii_char[14]="U"
convert.ascii_car[15]="ç"
convert.ascii_char[15]="c"
convert.ascii_car[16]="Ç"
convert.ascii_char[16]="C"
convert.ascii_car[17]="â"
convert.ascii_char[17]="a"
convert.ascii_car[18]="Â"
convert.ascii_char[18]="A"
convert.ascii_car[19]="û"
convert.ascii_char[19]="u"
convert.ascii_car[20]="Û"
convert.ascii_char[20]="U"
convert.ascii_car[21]="ë"
convert.ascii_char[21]="e"
convert.ascii_car[22]="Ë"
convert.ascii_char[22]="E"
convert.ascii_car[23]="ï"
convert.ascii_char[23]="i"
convert.ascii_car[24]="Ï"
convert.ascii_char[24]="I"
convert.ascii_car[25]="ö"
convert.ascii_char[25]="o"
convert.ascii_car[26]="Ö"
convert.ascii_char[26]="O"
convert.ascii_car[27]="ü"
convert.ascii_char[27]="U"
convert.ascii_car[28]="Ü"
convert.ascii_char[28]="U"
convert.ascii_car[29]="…" --"suspension points", not portable at all!
convert.ascii_char[29]= "."


-- control of ASCII table --
--[[
st = ""
for i=1,#convert.ascii_car do
    --print("initial ASCII char = " .. convert.ascii_car[i] .. " / converted char = " .. convert.ascii_char[i])
    st = st .. "//initial ASCII char = " .. convert.ascii_car[i] .. " / converted char = " .. convert.ascii_char[i]
end
fltk:fl_alert(st)
]]


-- if using luajit, comment next line
osName="OS=" .. murgaLua.getHostOsName()
-- if using luajit, uncomment next line
--osName="OS=linux"

t00=0
t11=0

--Fl:scheme("plastic")
Fl:scheme("gtk+")

find = string.find
sub = string.sub
pi = math.pi
rand = math.random

function deaccentuate(str)
  local i,j,str2,s,c
  
  str2=str
  --finding accentuated chars and deaccentuate them
  for i=1,#str do
      for j=1,#convert.ascii_car do
          s,c = string.gsub(str2, convert.ascii_car[j], convert.ascii_char[j])
          if s then
	     str2 = s
	  end
      end
  end
  return(str2)
end --end function

function define_textfile_origin(data)
  local i,st

  --finding if -CURRENTLY OPENED- text file
  -- is Unix or Windows -generated
  --searching for CR/LF (windows)
  st = string.char(13) .. string.char(10)
  i = find(data, st)
  if i then
--print("file generated by MS Windows => size_eol=2")
     size_eol=2 -- for windows remove CR+LF at end of line
     return("windows")
  else
--print("file generated by an Unix-like OS => size_eol=1")
     size_eol=1 -- for unixes remove only LF(?)
     return("unix")
  end
end --end function

function round(nb)
  if nb then
     if nb >= 0 then
	    return math.floor(nb)
	 else
	    return math.ceil(nb)
	 end
  else
     return 0
  end
end --end function

function display_charts()
  local i, p, w, st
  
  --adjusting  buttons size, propertie, color according to tables dirs_size, dirs_size_label, dirs_labels
  p = dirs_size[i] -- size as number
  for i=1,30 do
      st = dirs_labels_ASCII[i] .. "\nsize = " .. dirs_size_label[i] --size as tring
      dirs_button[i]:tooltip(st)
      --word_box[ #word_box]:box(visibility_word_box)
      dec_button = dec_button + height_button 
  end  
end --end function

function populate_tables()
  local p,p0,q,w1,w2
  local multi=1
  local size,st,st2,s,c
  
  --here, give values to tables
  --dirs_labels
  --dirs_size
  --dirs_ordering
  if osName == "OS=linux" then
     --structure of linux results in file
--[[
11G	cbr/
2,3G	Bureau/
1,6G	Téléchargements/
964M	Documents/
]]
     p0=1
     while 1 do
        p = find(read_data, "\n", p0, true)
        if p then
           line = sub(read_data, p0, p-1)
	   q = find(line,"\t",1,true)
	   w1 = string.upper(sub(line, 1, q-1))
	   if find(w1,"P",1,true) then
	      multi=1024^5
	      --multi=2^5
	   elseif find(w1,"T",1,true) then
	      multi=1024^4
	      --multi=2^4
	   elseif find(w1,"G",1,true) then
	      multi=1024^3
	      --multi=2^3
	   elseif find(w1,"M",1,true) then
	      multi=1024^2
	      --multi=2^2
	   elseif find(w1,"K",1,true) then
	      multi=1024
	      --multi=2
	   else
	      multi=1
	   end
	   st = sub(w1, 1, -2)
	   s,c = string.gsub(st, ",", ".")
	   if s then 
	      st = s
	   end
print("conversion string of size to number = " .. st .. ", size of string = " .. #st)
	   size = multi * tonumber( st )
print("conversion string of size to number = " .. size)
	   w2 = sub(line, q+1)
print( (#dirs_labels+1) .. ". size=" .. w1 .. " // label=" .. w2)
           if w2 ~= nil and size ~= nil then
              table.insert(dirs_labels, w2)
	      table.insert(dirs_size, size) --size as a number defining width of button
	      table.insert(dirs_size_label,w1) -- size "string formatted" like 4,3G or 144k
	      st2 = deaccentuate( dirs_labels[ #dirs_labels ] )
	      if st2 then
	         table.insert(dirs_labels_ASCII, st2)
	      else
		 table.insert(dirs_labels_ASCII, "pb technique")
	      end
	   end
           p0 = p+1
        else
           break
        end
    end
  elseif osName == "OS=windows" then
     --windows
  elseif osName == "OS=macos" then
     --not sure about this dev
  else
     --????
  end
end --end function

function load_data()
  local st, sysfile = "", ""
  local nbl,nbc = 0, 0  
  
  i=0
  f=0
  st=""
  
  if cmdline() ~= 1 then
     return nil
  end
  
  if osName == "OS=linux" then
     linecmd = "hostname > temp.txt";
     res = os.execute(linecmd)
     if res == 0 then
        f = io.open("temp.txt", "rb")
        if f then
           buffer = f:read("*all")
print("Hostname ? " .. buffer)
	   if find(buffer, "terras-Aspire-5733Z",1,true) then
	      filename = "/home/terras/testcmd.txt" -- ACER
	   elseif find(buffer, "HP6200",1,true) then
	      filename = "/home/terras/testcmd.txt"
	   else
	      filename=nil
	   end
           io.close(f)
	end
     end
  elseif osName == "OS=windows" then
     --filename = "G:\\Dim\\dsl-not\\scripts-murgaLua\\testcmd.txt"
	 filename = "G:\\Dim\\dsl-not\\scripts-murgaLua\\testcmd_linux.txt"
  elseif osName == "OS=macos" then
     --nothing for macos
	 return nil
  else
     return nil
  end
  
  local f = 0
  local i = 0
  local j = 0
  local k = 0
  local pos=1
  local posc=1
  read_data = ""
  local str
  
  
  if filename then
     --init previous tables, if any
      
     f = io.open(filename,"rb")
     if f then
        read_data = f:read("*all")
        read_data = string.lower(read_data)
print("Reading successfully file " .. filename .. ", taille=" .. #read_data .. " bytes")
        io.close(f)
        sysfile = define_textfile_origin(read_data)
print("filesystem Origin (according to CR/LF) = " .. sysfile )
        populate_tables()
        return 1
     else
        print("Inexistent of file " .. filename)
        return nil, nil
     end
  else
    return nil, nil
  end
end --end function

function cmdline()
  local res
  local cmdl=""
  if osName == "OS=linux" then
     --30 "most full" directories
     cmdl="du -k */ | sort -nr | cut -f2 | xargs -d '\n' du -sh | head -n 30 > /home/terras/testcmd.txt"
     res = os.execute(cmdl)
     if res == 0 then
        --success
print("du command was successfull!")
        return 1
     else
        --epic fail
print("du command was an epic fail!")
        return 0
     end
  elseif osName == "OS=windows" then
     --30 "most full" directories
     cmdl="dir /S /A:D /O:S | FIND "/" > testcmd.txt"
     res = os.execute(cmdl)
     if res == 0 then
        --success
        return 1
     else
        --epic fail
       print("Resultat de " .. cmdl .. " = " .. res)
        return 0
     end
  else
      --MacOS
  end
end

function quit_callback_app()
  if pwindow then
     pwindow:hide()
     pwindow:clear()
     print("Quiting")
     os.exit(0)
  end
end --end function

  t00 = os.time() --top chrono

  --version FLTK
  print("Fltk version "  .. fltk.FL_MAJOR_VERSION .. "." .. fltk.FL_MINOR_VERSION .. fltk.FL_PATCH_VERSION)
  --premiere partie : chargement des données  
  if load_data() then
     print(#read_data .. " octets")
  else
     os.exit(0)
  end
  print("Traitement en " .. os.difftime(os.time(), t00) .. " secondes, soit en " .. (os.difftime(os.time(), t00)/60) .. " mn, soit en " .. (os.difftime(os.time(), t00)/3600).. " heures")
    
  os.setlocale'fr_FR'
  --os.setlocale'fr_FR.ISO-8859-1'
  --os.setlocale'C'
  --st="Ceci est une pause" 
  --fltk:fl_alert(st)
  
  --GUI --------------------------------------------------------------------
  width_pwindow = 500
  height_pwindow = 500
  width_button = 160
  dec_button = 0
  
  pwindow = fltk:Fl_Window(width_pwindow, height_pwindow, "WordCloud")
  
  --centrage du bouton en bas de la fenetre pwindow
  width_button = 40
  height_button = 40
  quit = fltk:Fl_Button(dec_button+5, height_pwindow-height_button, width_button, height_button, "Quit")
  quit:tooltip("Quitter cette appli!")
  quit:callback(quit_callback_app)
  


  -- shape of charts = square (bars) or circle (pie)
  dec_button = dec_button+180
  width_button = 30
  height_button = 40
  shapedisp = fltk:Fl_Button(dec_button+5, height_pwindow-height_button, width_button, height_button, "@square")
  shapedisp:labelcolor(19)
  shapedisp:tooltip("click for toggle Bar/pie charts")
  shapedisp:callback(
        function(shapeupd)
	      if shapedisp:label() == "@square" then
		 shapedisp:label("@circle")
	      else
		 shapedisp:label("@square")
	      end
	      update_charts()
        end)  
	
  --display 30 empty "directory buttons"
  dec_button = 0
  height_button = 15
  for i=1,30 do
      st = i .. "."
      table.insert(dirs_button, fltk:Fl_Button(30,dec_button,300,height_button, st))
      --word_box[ #word_box]:box(visibility_word_box)
      dec_button = dec_button + height_button 
  end  
  
  --now display charts
  display_charts()
  
  
--[[
  --st="Ceci est un test de message d'alerte"
  st=""
  for i=1,#type_chart do
    st = st .. "type[" .. i .. "] = " .. type_chart[i] .. ", "
  end
  fltk:fl_alert(st)
  ]]

  --Fl:check()
  pwindow:show()
  
Fl:check()
Fl:run()
